### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined

### ISSUE THREAD

**Issue by Time02** [bitsent/bitsent.github.io#1]
In Chrome 73

link.js:63 Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined
    at encryptData (link.js:63)
    at addEncryptedText (link.js:186)
    at addEncryptedTexts (link.js:193)
    at link.js:145
    at readFile (link.js:202)
    at FileReader.reader.onload (link.js:211)

**Comment by Siko91** [comment]
it seems I have to work around the compatibility issues of SubtleCrypto in different browsers.

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#Browser_compatibility

Can you tell me more about your browser?
Crome is supposed to be supporting SubtleCrypto according to the docs at this link.
What version are you using? On what OS?
Have you added any plugins that may restrict what pages can do?

**Comment by Time02** [comment]
Mac os 10.14.4
Chrome 73.0.3683.86
Only LassPass plugins

**Comment by Siko91** [comment]
I found the reason.
It is not related to your browser.

"crypto.subtle is supposed to be undefined in insecure contexts"
https://www.chromium.org/blink/webcrypto

The website is not configured with HTTPS yet.
The Cryptography API does not work without HTTPS.

If you are in a hurry, save the website (Ctrl+S) and open the local file in your own computer.
It will work fine.

If you are not in a hurry, simply wait for "bitsent.net" to have HTTPS

**Comment by Siko91** [comment]
I added a warning message that explains others what happened.
https://github.com/bitsent/bitsent.github.io/commit/5e8553bb50bdeb88fbdd150f7bac9fa5efe2e6bf

**Comment by Siko91** [comment]
Alternatively, you can connect to the website with Firefox, and it is likely to run.
...but I don't recommend doing that.
The lack of SSL exposes your decryption keys for people who might be listening on your network traffic.

It is safer to save the webpage and run it locally on your own computer.

**Comment by Siko91** [comment]
Fixed!

HTTPS is enabled now.

No need for any workarounds.
Simply go to https://BitSent.Net/ and use the tool.
